name: Build conntrack-migrator

on:
  pull_request

jobs:
  build:

    timeout-minutes: 10
    runs-on: fedora-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo yum -y install gcc glib2-devel libmnl-devel libnetfilter_conntrack-devel check dbus
      - name: Build
        run: |
          make all
      - name: Unit tests
        run: sudo make check

