name: Build conntrack-migrator

on:
  pull_request

jobs:
  centos-7:

    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: centos:7

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yum -y install make gcc-4.8.5 epel-release
          yum -y install glib2-devel libmnl-devel libnetfilter_conntrack-devel check-devel dbus
      - name: Build
        run: |
          make all
          setcap cap_net_admin+eip build/conntrack_migrator
      - name: Unit tests
        run: make check

