name: Build conntrack-migrator

on:
  pull_request

jobs:
  build_test-ubuntu:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install -y gcc libglib2.0-dev libmnl-dev libnetfilter-conntrack-dev check dbus
      - name: Build
        run: |
          make all
      - name: Unit tests
        run: sudo make check # Since some of the tests require cap_net_admin
                             # hence running the tests as sudo.

  build-rocky-linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          dnf --enablerepo=powertools install -y make gcc glib2-devel libmnl-devel libnetfilter_conntrack-devel check dbus
      - name: Build
        run: |
          make all
          # since github actions does not allow to set capability cap_net_admin
          # to container, skipping tests.

